const results = document.querySelector('#results'), title = document.querySelector('#title'), dateText = document.querySelector('#date'), updated = document.querySelector('#updated'), gamesBox = document.querySelector('#games'), message = document.querySelector('#game-message');
const format = new Intl.DateTimeFormat('es-AR', { weekday: 'long', day: 'numeric', month: 'long' });
const key = 'quiniela-abuelo-jugadas-v1'; let data, archive = {}, day = 'today';
const games = () => JSON.parse(localStorage.getItem(key) || '[]');
const displayDate = iso => format.format(new Date(`${iso}T12:00:00`)).replace(',', '');
function status(game) { const record = archive[game.date] || [data?.today, data?.yesterday].find(x => x?.date === game.date); const draw = record?.draws?.find(x => x.name === game.draw); if (!draw) return ['Resultado todavía no disponible en la app.', '']; if (!draw.numbers?.length) return ['El sorteo todavía no está disponible.', '']; const number = draw.numbers[game.position - 1]; return number === game.number ? [`¡Coincidió! Salió ${number} en el puesto ${game.position}.`, 'match'] : [`No coincidió: en el puesto ${game.position} salió ${number}.`, 'miss']; }
function showGames() { const list = games().sort((a,b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt)); document.querySelector('#clear-games').hidden = !list.length; gamesBox.innerHTML = list.length ? list.map(game => { const [text, kind] = status(game); return `<article class="game"><h4>${displayDate(game.date)} · ${game.draw}</h4><p>Número jugado: <strong>${game.number}</strong> · Posición: <strong>${game.position}</strong></p><p class="status ${kind}">${text}</p></article>`; }).join('') : '<p class="empty">Todavía no cargaste ninguna jugada.</p>'; }
function showResults() { const selected = data?.[day]; title.textContent = day === 'today' ? 'Resultados de hoy' : 'Resultados de ayer'; if (!selected) { results.innerHTML = '<p class="empty">No se pudieron cargar los resultados.</p>'; return; } dateText.textContent = displayDate(selected.date); updated.textContent = data.updatedAt ? `Última actualización: ${new Date(data.updatedAt).toLocaleTimeString('es-AR', {hour:'2-digit',minute:'2-digit'})}` : ''; const ordered = [...selected.draws.filter(draw => draw.numbers?.length).reverse(), ...selected.draws.filter(draw => !draw.numbers?.length)]; results.innerHTML = ordered.map(draw => `<article class="draw"><h2>${draw.name}</h2>${draw.numbers?.length ? `<div class="result-box"><ol class="numbers">${draw.numbers.map((n,i) => `<li><span class="position">${String(i+1).padStart(2,'0')}</span><span class="number">${n}</span></li>`).join('')}</ol></div>` : '<p class="pending">El resultado todavía no está disponible.</p>'}</article>`).join(''); }
async function load() { updated.textContent = 'Actualizando resultados…'; try { const [latest, saved] = await Promise.all([fetch(`data/results.json?cache=${Date.now()}`, {cache:'no-store'}), fetch('data/archive.json', {cache:'no-store'})]); if (!latest.ok) throw Error(); data = await latest.json(); archive = saved.ok ? await saved.json() : {}; showResults(); showGames(); } catch { updated.textContent = 'No se pudo actualizar. Revisá la conexión e intentá de nuevo.'; } }
document.querySelectorAll('.nav-button').forEach(x => x.addEventListener('click', () => { document.querySelectorAll('.nav-button,.view').forEach(y => y.classList.remove('active')); x.classList.add('active'); document.querySelector(`#${x.dataset.view}`).classList.add('active'); if (x.dataset.day) { day = x.dataset.day; showResults(); } }));
document.querySelector('#refresh').addEventListener('click', () => location.reload());
document.querySelector('#game-date').value = new Intl.DateTimeFormat('en-CA', {timeZone:'America/Argentina/Buenos_Aires'}).format(new Date());
document.querySelector('#game-form').addEventListener('submit', e => { e.preventDefault(); const number = document.querySelector('#game-number').value.trim().padStart(4,'0'), position = Number(document.querySelector('#game-position').value); if (!/^\d{4}$/.test(number) || position < 1 || position > 20) { message.textContent = 'Revisá el número y la posición.'; return; } const list = games(); list.push({id:crypto.randomUUID(),date:document.querySelector('#game-date').value,draw:document.querySelector('#game-draw').value,number,position,createdAt:new Date().toISOString()}); localStorage.setItem(key, JSON.stringify(list)); e.target.reset(); document.querySelector('#game-date').value = data?.today?.date || ''; message.textContent = 'La jugada quedó guardada.'; showGames(); });
document.querySelector('#clear-games').addEventListener('click', () => { if (confirm('¿Querés borrar todas las jugadas guardadas en este teléfono?')) { localStorage.removeItem(key); message.textContent = 'Se borraron las jugadas guardadas.'; showGames(); } });
load(); setInterval(load, 300000);

// === Escenas por sorteo: agrega a cada tarjeta una clase según su nombre (draw-previa, draw-nocturna, etc.) ===
const paintDraws = () => results.querySelectorAll('.draw').forEach(card => {
  const name = card.querySelector('h2').textContent.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/^la /, '').trim();
  card.classList.add(`draw-${name}`);
});
const baseShowResults = showResults;
showResults = () => { baseShowResults(); paintDraws(); };
